spring:
  application:
    name: core-bridge-core
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import:
      - "classpath:application-token.yml"
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  batch:
    job:
      enabled: false              # Job 자동 실행 방지
    jdbc:
      initialize-schema: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  web:
    resources:
      static-locations: file:${upload.path}/PDF/

  elasticsearch:
    uris: ${ELASTIC_URI}
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    rest:
      ssl:
        verification-mode: none

  data:
    elasticsearch:
      repositories:
        enabled: false

  jpa:
    properties:
      hibernate.hibernate.default_batch_fetch_size: 100

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

upload:
  path: ${UPLOAD_PATH}

password:
  reset:
    redirect:
      url: ${PWD_RESET_REDIRECT_URL}


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    # 사용할 health indicator를 whitelist 형식으로 선택
    # 사용하지 않을 것은 false로 비활성화
    mail:
      enabled: false

    elasticsearch:
      enabled: false

ai:
  base-url: "http://175.197.41.64:33398"

n8n:
  base-url: "http://175.197.41.64:34567/webhook-test"
